### ISSUE TITLE
slot's using default generic functions

### ISSUE THREAD

**Issue by rabbibotton** [melisgl/mgl-pax#15] opened 2022-02-25 03:16 UTC
It would be great if slot's using default generic functions would pull documentation from the slot definition when listed as generic-function in the defsection.

**Comment by melisgl** [comment] 2022-02-25 08:04
So the problem is that when using the `generic-function` locative instead of e.g. `reader` the docstring is not found.

```
(defclass xxx ()
  ((a :reader xxx-a :documentation "This is XXX-A.")))

(pax:document (pax:locate 'xxx-a '(pax:reader xxx)))
.. - [reader] XXX-A XXX
..
..     This is XXX-A.
..

(pax:document (pax:locate 'xxx-a '(generic-function () (xxx))))
.. - [generic-function] XXX-A OBJECT
..
```

I guess you consider the choice between having a reader or a separate generic function an implementation detail and would not like to expose readerness in the documentation, right?

**Comment by melisgl** [comment] 2022-02-25 08:17
Whoops, I meant to use the `method` locative.

```
(pax:document (pax:locate 'xxx-a '(method () (xxx))))
.. - [method] XXX-A (XXX XXX)
..
..     This is XXX-A.
..
```

It seems to work as intended. The problem with the using `generic-function` is that there can be multiple classes, each with its own reader (with the same name), so there is no single docstring which shall be presented.

**Comment by melisgl** [comment] 2023-04-23 12:16
Closing. Feel free to reopen if my reasoning above is incorrent.

**Closed by melisgl** 2023-04-23 12:16 UTC
